DROP TABLE IF EXISTS ARTICLES;
DROP TABLE IF EXISTS REFERENCES;

CREATE TABLE ARTICLES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  url VARCHAR(250) NOT NULL
);
CREATE TABLE REFERENCES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  url_1 VARCHAR(250) NOT NULL,
  url_2 VARCHAR(250) NOT NULL,
  type_of BOOLEAN NOT NULL,
  similarity DOUBLE NOT NULL
);